### ISSUE TITLE
excuse me, error:  Unable to resolve module

### ISSUE THREAD

**Issue by zhangbuding** [luulam/todo#1]
i clone this project and npm install , then when i execute it, its wrong,
the log like this 

> Bundling `index.js`  [development, non-minified]  99.6% (477/478), failed.
error: bundling failed: UnableToResolveError: Unable to resolve module `./configs/Navigation` from `/Users/Cy/Desktop/prac/64-rn/todo/src/index.js`: could not resolve `/Users/Cy/Desktop/prac/64-rn/todo/src/configs/Navigation' as a file nor as a folder
    at ModuleResolver._loadAsFileOrDirOrThrow (/Users/Cy/Desktop/prac/64-rn/todo/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:337:11)
    at ModuleResolver._resolveFileOrDir (/Users/Cy/Desktop/prac/64-rn/todo/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:222:17)
    at ModuleResolver.resolveNodeDependency (/Users/Cy/Desktop/prac/64-rn/todo/node_modules/metro-bundler/src/node-haste/DependencyGraph/ModuleResolution.js:236:19)
    at ResolutionRequest.resolveDependency (/Users/Cy/Desktop/prac/64-rn/todo/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:109:14)
    at dependencyNames.map.name (/Users/Cy/Desktop/prac/64-rn/todo/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:134:10)
    at Array.map (<anonymous>)
    at ResolutionRequest.resolveModuleDependencies (/Users/Cy/Desktop/prac/64-rn/todo/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:133:42)
    at module.readFresh.then (/Users/Cy/Desktop/prac/64-rn/todo/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:181:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

how can i fix it ? thank you so much

**Comment by ginbluee** [comment]
go to die ✌️
